import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
import {api} from '../server/api.mjs';import {database,localBucket} from '../server/sqlite.mjs';import {DEFAULTS} from '../server/defaults.mjs';import {INITIAL_IMPORT} from './catalog-fixture.mjs';
const origin='https://esquiu.test',ownerHeaders={'oai-authenticated-user-id':'owner-id','oai-authenticated-user-email':'owner@example.com'},adminHeaders={...ownerHeaders,'origin':origin,'x-esquiu-admin':'1','content-type':'application/json'};
function setup(){const DB=database(':memory:');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'esquiu-media-'));return {DB,BUCKET:localBucket(dir),DEFAULTS,INITIAL_IMPORT,ADMIN_EMAILS:'owner@example.com',RATE_LIMIT_SALT:'testing-only-0123456789',dir}}
async function call(env,path,method='GET',body,headers={}){return api(new Request(origin+path,{method,headers:method==='GET'?headers:{'origin':origin,'content-type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)}),env)}
async function importData(env,data=INITIAL_IMPORT){const r=await call(env,'/api/admin/import/preview','POST',data,adminHeaders);assert.equal(r.status,200);const p=await r.json();const c=await call(env,'/api/admin/import/commit','POST',{...data,revision:p.revision},adminHeaders);assert.equal(c.status,200);return c.json()}
async function publishOne(env){await importData(env);const p=await env.DB.prepare('SELECT * FROM products LIMIT 1').first();const r=await call(env,'/api/admin/products/'+p.id,'PUT',{sku:p.sku,name:p.name,brand:p.brand,description:'Descripción de prueba',category:'herramientas',priceCents:p.price_cents,image:null,published:true,active:true,offer:false,version:p.version},adminHeaders);assert.equal(r.status,200);return await env.DB.prepare('SELECT * FROM products WHERE id=?').bind(p.id).first()}
const orderBody=p=>({receiptToken:'a'.repeat(64),contact:{email:'buyer@example.com',firstName:'Prueba',lastName:'Comprador',phone:''},delivery:{type:'pickup'},items:[{id:p.id,quantity:2}],notes:''});
test('80 productos sintéticos importados como borradores, sin stock inventado',async()=>{const env=setup(),result=await importData(env);assert.equal(result.created,80);assert.equal((await env.DB.prepare('SELECT COUNT(*) n FROM products').first()).n,80);assert.deepEqual(await(await call(env,'/api/public/products')).json(),[]);const schema=await env.DB.prepare('PRAGMA table_info(products)').all();assert.equal(schema.results.some(c=>c.name==='stock'),false);env.DB.close()});
test('la importación actualiza por código y conserva la publicación',async()=>{const env=setup(),p=await publishOne(env),data={source:'actualización',rows:[{sku:p.sku,name:p.name,brand:p.brand,priceCents:p.price_cents+100}]};const result=await importData(env,data);assert.equal(result.created,0);assert.equal(result.updated,1);const updated=await env.DB.prepare('SELECT * FROM products WHERE id=?').bind(p.id).first();assert.equal(updated.published,1);assert.equal(updated.price_cents,p.price_cents+100);assert.equal(updated.category,'herramientas');env.DB.close()});
test('un usuario anónimo o no autorizado no puede leer ni editar el panel',async()=>{const env=setup();assert.equal((await call(env,'/api/admin/products')).status,401);assert.equal((await call(env,'/api/admin/products','GET',undefined,{'oai-authenticated-user-id':'other','oai-authenticated-user-email':'other@example.com'})).status,403);assert.equal((await call(env,'/api/admin/products','POST',{},ownerHeaders)).status,403);assert.equal((await call(env,'/api/admin/products','POST',{}, {...adminHeaders,origin:'https://evil.test'})).status,403);env.DB.close()});
test('permiso de productos no permite acceder a clientes ni usuarios',async()=>{const env=setup();await call(env,'/api/admin/users','POST',{email:'catalog@example.com',name:'Catálogo',role:'catalog',active:true},adminHeaders);const h={'oai-authenticated-user-id':'catalog-id','oai-authenticated-user-email':'catalog@example.com'};assert.equal((await call(env,'/api/admin/products','GET',undefined,h)).status,200);assert.equal((await call(env,'/api/admin/customers','GET',undefined,h)).status,403);assert.equal((await call(env,'/api/admin/users','GET',undefined,h)).status,403);env.DB.close()});
test('precio del pedido calculado en servidor, stock sin seguimiento y reintento idempotente',async()=>{const env=setup(),p=await publishOne(env),body={...orderBody(p),subtotalCents:1},headers={'idempotency-key':crypto.randomUUID()};const response=await call(env,'/api/orders','POST',body,headers);assert.equal(response.status,201);const data=await response.json();assert.equal(data.order.subtotalCents,p.price_cents*2);assert.equal(data.order.status,'pending');assert.equal(data.order.totalCents,null);const retry=await call(env,'/api/orders','POST',body,headers);assert.equal(retry.status,200);assert.equal((await retry.json()).order.id,data.order.id);assert.equal((await env.DB.prepare('SELECT COUNT(*) n FROM orders').first()).n,1);const changed=await call(env,'/api/orders','POST',{...body,notes:'cambio'},headers);assert.equal(changed.status,409);env.DB.close()});
test('un producto no publicado y una cantidad inválida no generan pedido',async()=>{const env=setup();await importData(env);const p=await env.DB.prepare('SELECT * FROM products LIMIT 1').first(),h={'idempotency-key':crypto.randomUUID()};assert.equal((await call(env,'/api/orders','POST',orderBody(p),h)).status,409);assert.equal((await call(env,'/api/orders','POST',{...orderBody(p),items:[{id:p.id,quantity:-1}]},{'idempotency-key':crypto.randomUUID()})).status,400);env.DB.close()});
test('cupón aplicado en servidor y precio del pedido conservado después de cambiar catálogo',async()=>{const env=setup(),p=await publishOne(env);await call(env,'/api/admin/coupons','PUT',{code:'PRUEBA',percent:10,active:true,expiresAt:null},adminHeaders);const r=await call(env,'/api/orders','POST',{...orderBody(p),coupon:'PRUEBA'},{'idempotency-key':crypto.randomUUID()});assert.equal(r.status,201);const o=(await r.json()).order;assert.equal(o.discountCents,Math.round(p.price_cents*2*.1));await env.DB.prepare('UPDATE products SET price_cents=1 WHERE id=?').bind(p.id).run();const item=await env.DB.prepare('SELECT * FROM order_items WHERE order_id=?').bind(o.id).first();assert.equal(item.unit_cents,p.price_cents);env.DB.close()});
test('seguimiento privado, confirmación del total y registro manual de pago',async()=>{const env=setup(),p=await publishOne(env),r=await call(env,'/api/orders','POST',orderBody(p),{'idempotency-key':crypto.randomUUID()}),o=(await r.json()).order;assert.equal((await call(env,'/api/orders/'+o.id)).status,404);const h={Authorization:'Bearer '+'a'.repeat(64)};assert.equal((await call(env,'/api/orders/'+o.id,'GET',undefined,h)).status,200);assert.equal((await call(env,'/api/orders/'+o.id+'/accept','POST',{},h)).status,409);const confirm=await call(env,'/api/admin/orders/'+o.id,'PUT',{version:1,status:'confirmed',shippingCents:0},adminHeaders);assert.equal(confirm.status,200);assert.equal((await call(env,'/api/orders/'+o.id+'/accept','POST',{},h)).status,200);const current=await env.DB.prepare('SELECT * FROM orders WHERE id=?').bind(o.id).first();assert.equal(current.status,'awaiting_payment');assert.equal((await call(env,'/api/admin/orders/'+o.id,'PUT',{version:current.version,status:'paid',paymentMethod:'transfer',paymentNote:'Comprobante de prueba'},adminHeaders)).status,200);env.DB.close()});
test('edición concurrente devuelve conflicto sin perder cambios',async()=>{const env=setup(),p=await publishOne(env),payload={sku:p.sku,name:p.name,brand:p.brand,description:'',category:'herramientas',priceCents:p.price_cents,published:true,active:true,image:null,offer:false,version:p.version};assert.equal((await call(env,'/api/admin/products/'+p.id,'PUT',payload,adminHeaders)).status,200);assert.equal((await call(env,'/api/admin/products/'+p.id,'PUT',{...payload,name:'Nombre perdido'},adminHeaders)).status,409);assert.equal((await env.DB.prepare('SELECT name FROM products WHERE id=?').bind(p.id).first()).name,p.name);env.DB.close()});
test('se rechazan duplicados, precios inválidos y fotos externas de producto',async()=>{const env=setup();assert.equal((await call(env,'/api/admin/import/preview','POST',{source:'x',rows:[INITIAL_IMPORT.rows[0],INITIAL_IMPORT.rows[0]]},adminHeaders)).status,400);assert.equal((await call(env,'/api/admin/products','POST',{sku:'X',name:'X',priceCents:-1},adminHeaders)).status,400);assert.equal((await call(env,'/api/admin/products','POST',{sku:'X',name:'X',priceCents:100,category:'herramientas',image:'https://evil.test/x.png'},adminHeaders)).status,400);env.DB.close()});
test('datos persistidos sobreviven a cerrar y abrir la base',async()=>{const folder=fs.mkdtempSync(path.join(os.tmpdir(),'esquiu-persist-')),file=path.join(folder,'data.sqlite'),env={...setup(),DB:database(file)};await importData(env);env.DB.close();const reopened=database(file);assert.equal((await reopened.prepare('SELECT COUNT(*) n FROM products').first()).n,80);reopened.close()});
test('exportación completa requiere permiso y excluye tokens privados',async()=>{const env=setup(),p=await publishOne(env);await call(env,'/api/orders','POST',orderBody(p),{'idempotency-key':crypto.randomUUID()});assert.equal((await call(env,'/api/admin/backup')).status,401);const b=await(await call(env,'/api/admin/backup','GET',undefined,ownerHeaders)).json();assert.equal(b.tables.products.length,80);assert.equal(b.tables.orders.length,1);assert.equal('token_hash'in b.tables.orders[0],false);env.DB.close()});
