export class HttpError extends Error { constructor(status,message){super(message);this.status=status} }
const fail=(status,message)=>{throw new HttpError(status,message)},now=()=>Date.now(),id=()=>crypto.randomUUID();
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export const hash=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(v=>v.toString(16).padStart(2,'0')).join('');
export function text(value,label,max=200,required=true){if(typeof value!=='string'||value.length>max||required&&!value.trim())fail(400,`Revisá ${label}.`);return value.trim()}
export function cents(value,label='el precio'){if(!Number.isSafeInteger(value)||value<0||value>1_000_000_000_000)fail(400,`Revisá ${label}.`);return value}
const email=v=>{v=text(v,'el email',254).toLowerCase();if(!/^[^\s@<>"']+@[^\s@<>"']+\.[^\s@<>"']+$/.test(v))fail(400,'Email inválido.');return v};
const roles=['admin','catalog','orders'],statuses=['pending','confirmed','awaiting_payment','paid','fulfilled','cancelled'];
const rows=async(db,sql,...args)=>(await db.prepare(sql).bind(...args).all()).results;
const one=async(db,sql,...args)=>db.prepare(sql).bind(...args).first();
const run=async(db,sql,...args)=>db.prepare(sql).bind(...args).run();
const st=(db,sql,...args)=>db.prepare(sql).bind(...args);
const auditStatement=(db,user,action,resource,detail={})=>st(db,'INSERT INTO audit (id,actor,action,resource,detail,created_at) VALUES (?,?,?,?,?,?)',id(),user.email,action,resource,JSON.stringify(detail),now());
async function body(request,max=1_000_000){if(Number(request.headers.get('content-length'))>max)fail(413,'El archivo o los datos son demasiado grandes.');const raw=await request.text();if(new TextEncoder().encode(raw).byteLength>max)fail(413,'Los datos son demasiado grandes.');try{const p=JSON.parse(raw);if(!p||Array.isArray(p)||typeof p!=='object')throw Error();return p}catch{fail(400,'Datos inválidos.')}}
function sameOrigin(request,admin=false){const origin=request.headers.get('origin');if(origin!==new URL(request.url).origin)fail(403,'La solicitud debe venir desde esta web.');if(admin&&request.headers.get('x-esquiu-admin')!=='1')fail(403,'Falta la verificación de la solicitud.');if(request.headers.get('sec-fetch-site')==='cross-site')fail(403,'Solicitud externa no permitida.')}
async function staffUser(request,env,permission){const userId=request.headers.get('oai-authenticated-user-id'),rawEmail=request.headers.get('oai-authenticated-user-email');if(!userId||!rawEmail)fail(401,'Iniciá sesión para acceder al panel.');const userEmail=rawEmail.toLowerCase();const owners=String(env.ADMIN_EMAILS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);let user;
 if(owners.includes(userEmail))user={id:userId,email:userEmail,role:'owner'};
 else {const member=await one(env.DB,'SELECT * FROM staff WHERE email=? AND active=1',userEmail);if(!member||member.user_id&&member.user_id!==userId)fail(403,'Tu usuario no tiene acceso al panel.');if(!member.user_id)await run(env.DB,'UPDATE staff SET user_id=? WHERE email=? AND user_id IS NULL',userId,userEmail);const bound=await one(env.DB,'SELECT user_id FROM staff WHERE email=?',userEmail);if(bound.user_id!==userId)fail(403,'No se pudo verificar tu usuario.');user={id:userId,email:userEmail,role:member.role}}
 if(permission&&!['owner','admin',permission].includes(user.role))fail(403,'Tu permiso no permite esta acción.');return user;
}
async function owner(request,env){const u=await staffUser(request,env);if(u.role!=='owner')fail(403,'Solo el propietario puede administrar usuarios.');return u}
async function config(env){const result=await rows(env.DB,'SELECT key,value,version FROM settings');const out=structuredClone(env.DEFAULTS||{});out.versions={};for(const r of result){out[r.key]=JSON.parse(r.value);out.versions[r.key]=r.version}return out}
export function publicProduct(p){return {id:p.id,sku:p.sku,name:p.name,brand:p.brand,description:p.description,category:p.category,price:p.price_cents/100,image:p.image||'assets/product-placeholder.svg',imageAlt:p.name,offer:!!p.offer,stock:null,stockMode:'untracked',availability:'confirm',maxQuantity:99}}
function validImage(value){if(value===null||value==='')return null;const v=text(value,'la imagen',500);if(!/^\/media\/[0-9a-f-]{36}$/.test(v))fail(400,'Subí una foto de producto desde el panel.');return v}
function productInput(p,env){const sku=text(p.sku,'el código',80),name=text(p.name,'el nombre',240),category=text(p.category||'','el rubro',80,false);if(category&&!env.DEFAULTS.categories.some(c=>c.slug===category))fail(400,'Rubro inválido.');const priceCents=cents(p.priceCents);if(priceCents<1)fail(400,'El precio debe ser mayor que cero.');if(p.published&&!category)fail(400,'Elegí un rubro antes de publicar.');return {sku,name,brand:text(p.brand||'','la marca',100,false),description:text(p.description||'','la descripción',4000,false),category,priceCents,image:validImage(p.image),published:p.published?1:0,active:p.active===false?0:1,offer:p.offer?1:0}}
async function verifyMedia(db,image){if(image&&!await one(db,'SELECT id FROM media WHERE id=?',image.slice(7)))fail(400,'La foto no está disponible.')}
function productArgs(p){return [p.sku,p.name,p.brand,p.description,p.category,p.priceCents,p.image,p.published,p.active,p.offer]}
const publicOrder=o=>({id:o.id,code:o.code,status:o.status,delivery:o.delivery,subtotalCents:o.subtotal_cents,shippingCents:o.shipping_cents,discountCents:o.discount_cents,totalCents:o.shipping_cents===null?null:o.subtotal_cents+o.shipping_cents-o.discount_cents,createdAt:o.created_at});
async function buyerOrder(request,env,orderId){const token=request.headers.get('authorization')?.replace(/^Bearer /,'');if(!token||!/^[0-9a-f]{64}$/.test(token))fail(404,'Pedido no encontrado.');const order=await one(env.DB,'SELECT * FROM orders WHERE id=? AND token_hash=?',orderId,await hash(token));if(!order||now()-order.created_at>90*86400000)fail(404,'Pedido no encontrado o enlace vencido.');return order}
async function rateLimit(request,env){const ip=request.headers.get('cf-connecting-ip')||'local';if(!env.RATE_LIMIT_SALT)fail(503,'La recepción de pedidos todavía no está habilitada.');const time=now(),key=await hash(env.RATE_LIMIT_SALT+':'+ip+':'+Math.floor(time/3600000));await run(env.DB,'DELETE FROM rate_limits WHERE expires_at<?',time);const q=await one(env.DB,'INSERT INTO rate_limits (key,hits,expires_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET hits=hits+1 WHERE hits<10 RETURNING hits',key,time+3600000);if(!q)fail(429,'Demasiados pedidos. Esperá un momento o contactanos.');}
async function createOrder(request,env){sameOrigin(request);const p=await body(request,50000);if(p.website)fail(400,'No pudimos procesar la solicitud.');const key=text(request.headers.get('idempotency-key')||'','la identificación del pedido',80);if(!/^[0-9a-f-]{36}$/.test(key))fail(400,'Identificación de pedido inválida.');const token=text(p.receiptToken,'la identificación de seguimiento',64);if(!/^[0-9a-f]{64}$/.test(token))fail(400,'Seguimiento inválido.');const requestHash=await hash(JSON.stringify(p));const existing=await one(env.DB,'SELECT * FROM orders WHERE idempotency_key=?',key);if(existing){if(existing.request_hash!==requestHash)fail(409,'El pedido cambió. Volvé a revisar el carrito.');return json({kind:'order',order:publicOrder(existing)},200)}await rateLimit(request,env);
 const contact=p.contact||{},delivery=p.delivery||{};const buyerEmail=email(contact.email),first=text(contact.firstName,'el nombre',100),last=text(contact.lastName,'el apellido',100),phone=text(contact.phone||'','el teléfono',40,false),notes=text(p.notes||'','las notas',2000,false);if(!['pickup','shipping'].includes(delivery.type))fail(400,'Elegí cómo querés recibir el pedido.');const addr={};if(delivery.type==='shipping'){addr.address=text(delivery.address,'la dirección',300);addr.city=text(delivery.city,'la localidad',100);addr.postalCode=text(delivery.postalCode,'el código postal',20);addr.province=text(delivery.province||'','la provincia',100,false)}
 if(!Array.isArray(p.items)||!p.items.length||p.items.length>50)fail(400,'Revisá los productos del carrito.');const ids=new Set();const items=p.items.map(r=>{const productId=text(r.id,'el producto',100);if(ids.has(productId)||!Number.isInteger(r.quantity)||r.quantity<1||r.quantity>99)fail(400,'Revisá las cantidades del carrito.');ids.add(productId);return {id:productId,quantity:r.quantity}});
 const products=await rows(env.DB,`SELECT * FROM products WHERE id IN (${items.map(()=>'?').join(',')}) AND active=1 AND published=1`,...items.map(r=>r.id));if(products.length!==items.length)fail(409,'Un producto ya no está disponible para pedir. Actualizá el carrito.');let subtotal=0;const detail=items.map(r=>{const pr=products.find(x=>x.id===r.id);subtotal+=pr.price_cents*r.quantity;return {...r,product:pr}});cents(subtotal,'el total del pedido');const coupon=p.coupon?text(p.coupon,'el cupón',40).toUpperCase():null;let discount=0;if(coupon){const cp=await one(env.DB,'SELECT * FROM coupons WHERE code=? AND active=1',coupon);if(!cp||cp.expires_at&&cp.expires_at<now())fail(400,'El cupón no está disponible.');discount=Math.round(subtotal*cp.percent/100)}
 const orderId=id(),code='ESQ-'+orderId.slice(0,8).toUpperCase(),time=now();const batch=[st(env.DB,'INSERT INTO orders (id,code,idempotency_key,request_hash,token_hash,status,email,first_name,last_name,phone,delivery,address_json,notes,subtotal_cents,shipping_cents,discount_cents,coupon,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',orderId,code,key,requestHash,await hash(token),'pending',buyerEmail,first,last,phone,delivery.type,JSON.stringify(addr),notes,subtotal,null,discount,coupon,1,time,time),...detail.map(r=>st(env.DB,'INSERT INTO order_items (id,order_id,product_id,sku,name,quantity,unit_cents) VALUES (?,?,?,?,?,?,?)',id(),orderId,r.id,r.product.sku,r.product.name,r.quantity,r.product.price_cents))];try{await env.DB.batch(batch)}catch(error){const concurrent=await one(env.DB,'SELECT * FROM orders WHERE idempotency_key=?',key);if(concurrent&&concurrent.request_hash===requestHash)return json({kind:'order',order:publicOrder(concurrent)});throw error}const o=await one(env.DB,'SELECT * FROM orders WHERE id=?',orderId);return json({kind:'order',order:publicOrder(o)},201);
}
async function importRows(request,env,user,preview){const p=await body(request);if(!Array.isArray(p.rows)||!p.rows.length||p.rows.length>1000)fail(400,'Importá entre 1 y 1000 productos por archivo.');const skus=new Set();const source=text(p.source||'Excel','el origen',150);const data=p.rows.map((r,i)=>{const sku=text(r.sku,`el código de la fila ${i+1}`,80);if(skus.has(sku))fail(400,`Código repetido: ${sku}`);skus.add(sku);return {id:id(),sku,name:text(r.name,`el nombre de ${sku}`,240),brand:text(r.brand||'','la marca',100,false),priceCents:cents(r.priceCents),createdAt:now()}});if(data.some(r=>r.priceCents<1))fail(400,'Hay precios vacíos o iguales a cero.');const old=await rows(env.DB,'SELECT sku,price_cents,version FROM products ORDER BY sku');const revision=await hash(JSON.stringify(old));const created=data.filter(r=>!old.some(x=>x.sku===r.sku)).length;const changes=data.filter(r=>old.some(x=>x.sku===r.sku&&x.price_cents!==r.priceCents)).map(r=>({sku:r.sku,oldPriceCents:old.find(x=>x.sku===r.sku).price_cents,newPriceCents:r.priceCents}));if(preview)return json({total:data.length,created,updated:data.length-created,priceChanges:changes,revision,source});if(p.revision!==revision)fail(409,'El catálogo cambió después de la vista previa. Revisá nuevamente la importación.');const sql=`INSERT INTO products (id,sku,name,brand,price_cents,source,created_at,updated_at) SELECT json_extract(value,'$.id'),json_extract(value,'$.sku'),json_extract(value,'$.name'),json_extract(value,'$.brand'),json_extract(value,'$.priceCents'),?,json_extract(value,'$.createdAt'),json_extract(value,'$.createdAt') FROM json_each(?) WHERE (SELECT json_group_array(json_object('sku',sku,'price_cents',price_cents,'version',version)) FROM (SELECT sku,price_cents,version FROM products ORDER BY sku))=? ON CONFLICT(sku) DO UPDATE SET name=excluded.name,brand=excluded.brand,price_cents=excluded.price_cents,source=excluded.source,version=products.version+1,updated_at=excluded.updated_at RETURNING sku`;
 const result=await env.DB.batch([st(env.DB,sql,source,JSON.stringify(data),JSON.stringify(old)),st(env.DB,'INSERT INTO imports (id,source,count,created_by,created_at) SELECT ?,?,?,?,? WHERE changes()>0',id(),source,data.length,user.email,now()),st(env.DB,'INSERT INTO audit (id,actor,action,resource,detail,created_at) SELECT ?,?,?,?,?,? WHERE changes()>0',id(),user.email,'import','products',JSON.stringify({source,count:data.length,created,updated:data.length-created}),now())]);if(!result[0].results?.length)fail(409,'El catálogo cambió durante la importación. Revisá los cambios nuevamente.');return json({created,updated:data.length-created,total:data.length});}
async function saveSettings(request,env,user){const p=await body(request,50000),key=text(p.key,'la sección',40);let value;if(key==='business'){const b=p.value;value={...env.DEFAULTS.business,name:text(b.name,'el nombre',100),address:text(b.address,'la dirección',240),previousAddress:text(b.previousAddress||'','la dirección anterior',240,false),hours:text(b.hours,'los horarios',500),holidayHours:text(b.holidayHours||'','los feriados',200,false),hardware:{phone:text(b.hardware.phone,'el teléfono',30),displayPhone:text(b.hardware.phone,'el teléfono',30),email:email(b.hardware.email),whatsapp:b.hardware.whatsapp?text(b.hardware.whatsapp,'el WhatsApp',20):null},automotive:{phone:text(b.automotive.phone,'el teléfono',30),displayPhone:text(b.automotive.phone,'el teléfono',30),email:email(b.automotive.email),whatsapp:b.automotive.whatsapp?text(b.automotive.whatsapp,'el WhatsApp',20):null}};for(const contact of [value.hardware,value.automotive])if(contact.whatsapp&&!/^\d{10,15}$/.test(contact.whatsapp))fail(400,'WhatsApp debe tener código de país y solo números.')}else if(key==='presentation'){value={};for(const slot of ['hero','lubricentro','empresas']){value[slot]=validImage(p.value[slot]);await verifyMedia(env.DB,value[slot])}}else if(key==='categories'){if(!Array.isArray(p.value)||p.value.length!==8)fail(400,'Deben conservarse los ocho rubros.');value=env.DEFAULTS.categories.map(c=>{const entry=p.value.find(v=>v.slug===c.slug);if(!entry)fail(400,'Falta un rubro.');const image=entry.image===c.image?c.image:validImage(entry.image);return {...c,image:image||c.image}});for(const c of value)if(c.image.startsWith('/media/'))await verifyMedia(env.DB,c.image)}else if(key==='payment'){if(!['owner','admin'].includes(user.role))fail(403,'Solo administración puede cambiar los datos de pago.');value={instructions:text(p.value.instructions||'','las instrucciones de pago',2000,false)}}else fail(400,'Sección inválida.');const old=await one(env.DB,'SELECT version FROM settings WHERE key=?',key);if((old?.version||0)!==p.version)fail(409,'Otra persona cambió esta sección. Volvé a cargarla.');const result=await one(env.DB,'INSERT INTO settings (key,value,updated_at,version) VALUES (?,?,?,1) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at,version=settings.version+1 WHERE settings.version=? RETURNING version',key,JSON.stringify(value),now(),p.version);if(!result)fail(409,'La sección cambió. Volvé a cargarla.');await env.DB.batch([auditStatement(env.DB,user,'settings',key)]);return json({saved:true,version:result.version})}
async function upload(request,env,user){if(!env.BUCKET)fail(503,'El almacenamiento de imágenes no está conectado.');const type=request.headers.get('content-type');if(!['image/png','image/jpeg','image/webp'].includes(type))fail(400,'Usá PNG, JPG o WebP.');if(Number(request.headers.get('content-length'))>5_000_000)fail(413,'La imagen debe pesar menos de 5 MB.');const raw=new Uint8Array(await request.arrayBuffer());if(raw.length>5_000_000||raw.length<12)fail(413,'La imagen está vacía o supera los 5 MB.');const sig=Array.from(raw.slice(0,12));const ok=type==='image/png'?sig.slice(0,8).join(',')==='137,80,78,71,13,10,26,10':type==='image/jpeg'?sig[0]===255&&sig[1]===216&&sig[2]===255:String.fromCharCode(...sig.slice(0,4))==='RIFF'&&String.fromCharCode(...sig.slice(8,12))==='WEBP';if(!ok)fail(400,'El contenido no coincide con el formato de la imagen.');const mediaId=id(),key='images/'+mediaId,name=text(request.headers.get('x-file-name')||'imagen','el nombre',180);await env.BUCKET.put(key,raw,{httpMetadata:{contentType:type}});try{await env.DB.batch([st(env.DB,'INSERT INTO media (id,key,content_type,size,name,created_by,created_at) VALUES (?,?,?,?,?,?,?)',mediaId,key,type,raw.length,name,user.email,now()),auditStatement(env.DB,user,'upload',mediaId)])}catch(e){await env.BUCKET.delete(key);throw e}return json({id:mediaId,url:'/media/'+mediaId},201)}
export async function api(request,env){const url=new URL(request.url),path=url.pathname,method=request.method;try{
 if(!env.DB)fail(503,'La base de datos no está conectada.');
 if(path==='/api/public/site'&&method==='GET'){const cfg=await config(env);delete cfg.versions;delete cfg.payment;return json({...cfg,stockMode:'untracked',orderMode:'confirmation'})}
 if(path==='/api/public/products'&&method==='GET')return json((await rows(env.DB,'SELECT * FROM products WHERE published=1 AND active=1 ORDER BY name')).map(publicProduct));
 if(path==='/api/orders'&&method==='POST')return await createOrder(request,env);
 const buyer=path.match(/^\/api\/orders\/([0-9a-f-]{36})(\/accept)?$/);if(buyer){const o=await buyerOrder(request,env,buyer[1]);if(method==='GET'&&!buyer[2]){const lines=await rows(env.DB,'SELECT sku,name,quantity,unit_cents FROM order_items WHERE order_id=?',o.id);const cfg=await config(env);return json({order:publicOrder(o),items:lines,paymentInstructions:['awaiting_payment','paid','fulfilled'].includes(o.status)?cfg.payment?.instructions||'Contactanos para coordinar el pago.':null})}if(method==='POST'&&buyer[2]){sameOrigin(request);if(o.status!=='confirmed'||o.shipping_cents===null)fail(409,'El pedido todavía no está listo para confirmar.');await run(env.DB,"UPDATE orders SET status='awaiting_payment',version=version+1,updated_at=? WHERE id=? AND status='confirmed'",now(),o.id);return json({accepted:true})}}
 if(!path.startsWith('/api/admin/'))fail(404,'Recurso no encontrado.');if(!['GET','HEAD'].includes(method))sameOrigin(request,true);
 const permission=/\/products|\/import|\/media|\/settings|\/coupons/.test(path)?'catalog':/\/orders|\/customers/.test(path)?'orders':null;const user=await staffUser(request,env,permission);
 if(path==='/api/admin/session'&&method==='GET')return json({user,stockMode:'untracked',orderMode:'confirmation'});
 if(path==='/api/admin/initial-import'&&method==='GET'){if(!['owner','admin','catalog'].includes(user.role))fail(403,'No tenés permiso para importar.');return json(env.INITIAL_IMPORT||{source:'Sin archivo',rows:[]})}
 if(path==='/api/admin/dashboard'&&method==='GET')return json({products:await one(env.DB,'SELECT COUNT(*) total,SUM(published) published FROM products'),orders:user.role==='catalog'?[]:await rows(env.DB,'SELECT status,COUNT(*) count FROM orders GROUP BY status'),recent:user.role==='catalog'?[]:await rows(env.DB,'SELECT code,status,subtotal_cents,created_at FROM orders ORDER BY created_at DESC LIMIT 6')});
 if(path==='/api/admin/products'&&method==='GET')return json(await rows(env.DB,'SELECT * FROM products ORDER BY updated_at DESC'));
 if(path==='/api/admin/products'&&method==='POST'){const p=productInput(await body(request,10000),env);await verifyMedia(env.DB,p.image);const productId=id(),time=now();try{await env.DB.batch([st(env.DB,'INSERT INTO products (id,sku,name,brand,description,category,price_cents,image,published,active,offer,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',productId,...productArgs(p),time,time),auditStatement(env.DB,user,'create',productId,{sku:p.sku})])}catch(e){if(String(e).includes('UNIQUE'))fail(409,'Ya existe un producto con ese código.');throw e}return json({id:productId},201)}
 const prod=path.match(/^\/api\/admin\/products\/([0-9a-f-]{36})$/);if(prod&&method==='PUT'){const input=await body(request,10000),p=productInput(input,env);await verifyMedia(env.DB,p.image);let result;try{result=await one(env.DB,'UPDATE products SET sku=?,name=?,brand=?,description=?,category=?,price_cents=?,image=?,published=?,active=?,offer=?,version=version+1,updated_at=? WHERE id=? AND version=? RETURNING id,version',...productArgs(p),now(),prod[1],input.version)}catch(e){if(String(e).includes('UNIQUE'))fail(409,'Ese código pertenece a otro producto.');throw e}if(!result)fail(409,'El producto cambió. Recargá antes de guardar.');await env.DB.batch([auditStatement(env.DB,user,'update',prod[1],{sku:p.sku,priceCents:p.priceCents,published:!!p.published})]);return json(result)}
 if(path==='/api/admin/import/preview'&&method==='POST')return await importRows(request,env,user,true);if(path==='/api/admin/import/commit'&&method==='POST')return await importRows(request,env,user,false);
 if(path==='/api/admin/imports'&&method==='GET')return json(await rows(env.DB,'SELECT * FROM imports ORDER BY created_at DESC LIMIT 100'));
 if(path==='/api/admin/media'&&method==='POST')return await upload(request,env,user);if(path==='/api/admin/media'&&method==='GET')return json(await rows(env.DB,'SELECT id,name,content_type,size,created_at FROM media ORDER BY created_at DESC LIMIT 200'));
 if(path==='/api/admin/orders'&&method==='GET')return json(await rows(env.DB,'SELECT id,code,status,email,first_name,last_name,subtotal_cents,shipping_cents,discount_cents,created_at FROM orders ORDER BY created_at DESC LIMIT 500'));
 const orderMatch=path.match(/^\/api\/admin\/orders\/([0-9a-f-]{36})$/);if(orderMatch){const o=await one(env.DB,'SELECT * FROM orders WHERE id=?',orderMatch[1]);if(!o)fail(404,'Pedido no encontrado.');if(method==='GET'){const {token_hash,request_hash,idempotency_key,...safe}=o;return json({order:safe,items:await rows(env.DB,'SELECT * FROM order_items WHERE order_id=?',o.id)})}if(method==='PUT'){const p=await body(request,10000);const transitions={pending:['confirmed','cancelled'],confirmed:['awaiting_payment','cancelled'],awaiting_payment:['paid','cancelled'],paid:['fulfilled'],fulfilled:[],cancelled:[]};if(!statuses.includes(p.status)||!transitions[o.status].includes(p.status))fail(409,'Ese cambio de estado no está permitido.');let shipping=o.shipping_cents;if(p.status==='confirmed'){shipping=cents(p.shippingCents,'el costo de entrega');if(o.delivery==='pickup'&&shipping!==0)fail(400,'El retiro debe tener costo de envío cero.')}if(p.status==='paid'){if(!['cash','transfer','external'].includes(p.paymentMethod))fail(400,'Indicá cómo se recibió el pago.');text(p.paymentNote,'la referencia del pago',300)}const result=await one(env.DB,'UPDATE orders SET status=?,shipping_cents=?,payment_method=COALESCE(?,payment_method),payment_note=COALESCE(?,payment_note),version=version+1,updated_at=? WHERE id=? AND version=? RETURNING version',p.status,shipping,p.status==='paid'?p.paymentMethod:null,p.status==='paid'?p.paymentNote:null,now(),o.id,p.version);if(!result)fail(409,'Otra persona cambió el pedido. Recargá antes de guardar.');await env.DB.batch([auditStatement(env.DB,user,'order-status',o.id,{from:o.status,to:p.status})]);return json({saved:true,version:result.version})}}
 if(path==='/api/admin/customers'&&method==='GET')return json(await rows(env.DB,'SELECT email,MAX(first_name) first_name,MAX(last_name) last_name,MAX(phone) phone,COUNT(*) orders,MAX(created_at) last_order FROM orders GROUP BY email ORDER BY last_order DESC LIMIT 500'));
 if(path==='/api/admin/settings'&&method==='GET')return json(await config(env));if(path==='/api/admin/settings'&&method==='PUT')return await saveSettings(request,env,user);
 if(path==='/api/admin/users'){await owner(request,env);if(method==='GET')return json({owners:String(env.ADMIN_EMAILS||'').split(',').filter(Boolean),staff:await rows(env.DB,'SELECT email,name,role,active,created_at FROM staff ORDER BY email')});if(method==='POST'){const p=await body(request,3000),memberEmail=email(p.email);if(!roles.includes(p.role))fail(400,'Permiso inválido.');if(String(env.ADMIN_EMAILS||'').split(',').map(x=>x.trim().toLowerCase()).includes(memberEmail))fail(400,'El propietario se configura fuera de la lista de empleados.');await env.DB.batch([st(env.DB,'INSERT INTO staff (email,name,role,active,created_at) VALUES (?,?,?,?,?) ON CONFLICT(email) DO UPDATE SET name=excluded.name,role=excluded.role,active=excluded.active',memberEmail,text(p.name||'','el nombre',100,false),p.role,p.active===false?0:1,now()),auditStatement(env.DB,user,'staff',memberEmail,{role:p.role,active:p.active!==false})]);return json({saved:true})}}
 if(path==='/api/admin/coupons'&&method==='GET')return json(await rows(env.DB,'SELECT * FROM coupons ORDER BY code'));if(path==='/api/admin/coupons'&&method==='PUT'){const p=await body(request,3000),code=text(p.code,'el cupón',40).toUpperCase();if(!/^[A-Z0-9_-]+$/.test(code)||!Number.isInteger(p.percent)||p.percent<1||p.percent>100)fail(400,'Revisá el código y el descuento (1 a 100%).');const expires=p.expiresAt===null?null:p.expiresAt;if(expires!==null&&!Number.isSafeInteger(expires))fail(400,'Vencimiento inválido.');await env.DB.batch([st(env.DB,'INSERT INTO coupons (code,percent,active,expires_at) VALUES (?,?,?,?) ON CONFLICT(code) DO UPDATE SET percent=excluded.percent,active=excluded.active,expires_at=excluded.expires_at,version=coupons.version+1',code,p.percent,p.active?1:0,expires),auditStatement(env.DB,user,'coupon',code)]);return json({saved:true})}
 if(path==='/api/admin/audit'&&method==='GET'){if(!['owner','admin'].includes(user.role))fail(403,'No tenés acceso al historial.');return json(await rows(env.DB,'SELECT * FROM audit ORDER BY created_at DESC LIMIT 200'))}
 if(path==='/api/admin/backup'&&method==='GET'){if(!['owner','admin'].includes(user.role))fail(403,'No tenés permiso para exportar.');const tables=['products','orders','order_items','settings','staff','media','audit','imports','coupons'];const data={format:'esquiu-backup-v1',createdAt:now(),stockMode:'untracked',tables:{}};for(const table of tables)data.tables[table]=await rows(env.DB,'SELECT * FROM '+table);for(const o of data.tables.orders){delete o.token_hash;delete o.request_hash;delete o.idempotency_key}const response=json(data);response.headers.set('Content-Disposition','attachment; filename="esquiu-backup.json"');return response}
 fail(404,'Recurso no encontrado.');
 }catch(e){if(e instanceof HttpError)return json({error:e.message},e.status);console.error('Error de API',path,e?.message);return json({error:'No pudimos completar la operación. Tus cambios no se descartaron; volvé a intentar.'},503)} }
export async function mediaResponse(request,env){const match=new URL(request.url).pathname.match(/^\/media\/([0-9a-f-]{36})$/);if(!match||!['GET','HEAD'].includes(request.method))return new Response('No encontrado',{status:404});const entry=await one(env.DB,'SELECT * FROM media WHERE id=?',match[1]);if(!entry)return new Response('No encontrado',{status:404});const object=await env.BUCKET.get(entry.key);if(!object)return new Response('No encontrado',{status:404});return new Response(request.method==='HEAD'?null:object.body,{headers:{'Content-Type':entry.content_type,'Cache-Control':'public,max-age=86400','X-Content-Type-Options':'nosniff'}})}
