import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {randomBytes,timingSafeEqual,createHash} from 'node:crypto';
import worker from './worker.mjs';import {database,localBucket} from './sqlite.mjs';import {DEFAULTS} from './defaults.mjs';import {INITIAL_IMPORT} from './initial-catalog.mjs';import {api} from './api.mjs';import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('..',import.meta.url)),data=path.join(root,'.local-data');fs.mkdirSync(data,{recursive:true});const keyfile=path.join(data,'local-admin-key.txt');if(!fs.existsSync(keyfile))fs.writeFileSync(keyfile,randomBytes(24).toString('hex'),{mode:0o600});const key=fs.readFileSync(keyfile,'utf8').trim(),saltfile=path.join(data,'rate-salt.txt');if(!fs.existsSync(saltfile))fs.writeFileSync(saltfile,randomBytes(32).toString('hex'),{mode:0o600});
const DB=database(path.join(data,'esquiu.sqlite')),BUCKET=localBucket(path.join(data,'media')),port=Number(process.env.PORT||4190),owners=process.env.ADMIN_EMAILS||'gonzitassi@gmail.com';
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml','.webp':'image/webp'};
const ASSETS={async fetch(req){const url=new URL(req.url),base=path.join(root,'dist/client');let pathname;try{pathname=decodeURIComponent(url.pathname)}catch{return new Response('URL inválida',{status:400})}const file=path.resolve(base,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(base+path.sep))return new Response('No permitido',{status:403});try{return new Response(fs.readFileSync(file),{headers:{'Content-Type':mime[path.extname(file)]||'application/octet-stream'}})}catch{return new Response('No encontrado',{status:404})}}};
const env={DB,BUCKET,ASSETS,ADMIN_EMAILS:owners,RATE_LIMIT_SALT:fs.readFileSync(saltfile,'utf8'),DEFAULTS,INITIAL_IMPORT};
const hasProducts=await DB.prepare('SELECT COUNT(*) n FROM products').first();if(!hasProducts.n&&INITIAL_IMPORT.rows.length){const ownerEmail=owners.split(',')[0].trim(),headers={'oai-authenticated-user-id':'local-owner','oai-authenticated-user-email':ownerEmail,'origin':'http://127.0.0.1:'+port,'x-esquiu-admin':'1','content-type':'application/json'};const preview=await api(new Request('http://127.0.0.1:'+port+'/api/admin/import/preview',{method:'POST',headers,body:JSON.stringify(INITIAL_IMPORT)}),env);if(!preview.ok)throw Error('No se pudo preparar el catálogo inicial');const p=await preview.json();const commit=await api(new Request('http://127.0.0.1:'+port+'/api/admin/import/commit',{method:'POST',headers,body:JSON.stringify({...INITIAL_IMPORT,revision:p.revision})}),env);if(!commit.ok)throw Error('No se pudo guardar el catálogo inicial')}
const backups=path.join(data,'backups');fs.mkdirSync(backups,{recursive:true});const backupFile=path.join(backups,'esquiu-'+new Date().toISOString().slice(0,10)+'.sqlite');if(!fs.existsSync(backupFile))await DB.backup(backupFile);const copies=fs.readdirSync(backups).filter(n=>/^esquiu-\d{4}-\d{2}-\d{2}\.sqlite$/.test(n)).sort();for(const file of copies.slice(0,-7))fs.unlinkSync(path.join(backups,file));
const sessions=new Map(),loginAttempts=new Map(),digest=s=>createHash('sha256').update(s).digest();
const server=http.createServer(async(req,res)=>{try{const host=req.headers.host;if(!['127.0.0.1:'+port,'localhost:'+port].includes(host)){res.writeHead(403).end('Host no permitido');return}const origin='http://'+host,url=new URL(req.url,origin),headers=new Headers();for(const [name,value]of Object.entries(req.headers)){if(name.startsWith('oai-authenticated-user-')||name==='cf-connecting-ip')continue;if(typeof value==='string')headers.set(name,value)}headers.set('cf-connecting-ip',req.socket.remoteAddress||'local');let raw;let length=0;if(!['GET','HEAD'].includes(req.method)){const parts=[];for await(const part of req){length+=part.length;if(length>10_000_000){res.writeHead(413).end('Demasiado grande');return}parts.push(part)}raw=Buffer.concat(parts)}
 if(url.pathname==='/api/local-info'){res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'}).end('{"local":true}');return}
 if(url.pathname==='/api/local-session'&&req.method==='POST'){if(req.headers.origin!==origin){res.writeHead(403).end();return}const ip=req.socket.remoteAddress,time=Date.now(),attempt=loginAttempts.get(ip)||{count:0,until:time+60000};if(time>attempt.until){attempt.count=0;attempt.until=time+60000}attempt.count++;loginAttempts.set(ip,attempt);if(attempt.count>5){res.writeHead(429,{'Content-Type':'application/json'}).end('{"error":"Esperá un minuto antes de reintentar."}');return}let p;try{p=JSON.parse(raw.toString())}catch{p={}}if(typeof p.key!=='string'||!timingSafeEqual(digest(p.key),digest(key))){res.writeHead(401,{'Content-Type':'application/json'}).end('{"error":"Clave incorrecta."}');return}const token=randomBytes(32).toString('hex');sessions.set(token,Date.now()+8*3600000);res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store','Set-Cookie':'esquiu_local='+token+'; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800'}).end('{"ok":true}');return}
 if(url.pathname==='/signout-with-chatgpt'){const token=req.headers.cookie?.match(/(?:^|;\s*)esquiu_local=([0-9a-f]{64})/)?.[1];if(token)sessions.delete(token);res.writeHead(302,{'Location':'/admin/','Set-Cookie':'esquiu_local=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0'}).end();return}
 const token=req.headers.cookie?.match(/(?:^|;\s*)esquiu_local=([0-9a-f]{64})/)?.[1];if(token&&sessions.get(token)>Date.now()){headers.set('oai-authenticated-user-id','local-owner');headers.set('oai-authenticated-user-email',owners.split(',')[0].trim())}const response=await worker.fetch(new Request(url,{method:req.method,headers,body:raw}),env);res.writeHead(response.status,Object.fromEntries(response.headers));res.end(req.method==='HEAD'?undefined:Buffer.from(await response.arrayBuffer()))}catch(error){console.error('Error local:',error.message);if(!res.headersSent)res.writeHead(500);res.end('Error temporal del servidor')}});
server.listen(port,'127.0.0.1',()=>console.log(`ESQUIÚ: http://127.0.0.1:${port}\nPanel: http://127.0.0.1:${port}/admin/\nClave local guardada en .local-data/local-admin-key.txt\nCatálogo Lusqtoff cargado como borradores, sin stock.`));
process.on('SIGINT',()=>server.close(()=>{DB.close();process.exit(0)}));
