import { sqliteTable,text,integer,index } from 'drizzle-orm/sqlite-core';
export const products=sqliteTable('products',{
 id:text('id').primaryKey(),sku:text('sku').notNull().unique(),name:text('name').notNull(),brand:text('brand').notNull().default(''),description:text('description').notNull().default(''),category:text('category').notNull().default(''),priceCents:integer('price_cents').notNull(),image:text('image'),published:integer('published').notNull().default(0),active:integer('active').notNull().default(1),offer:integer('offer').notNull().default(0),version:integer('version').notNull().default(1),source:text('source').notNull().default('manual'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()
},t=>[index('idx_products_public_category').on(t.published,t.active,t.category)]);
export const orders=sqliteTable('orders',{
 id:text('id').primaryKey(),code:text('code').notNull().unique(),idempotencyKey:text('idempotency_key').notNull().unique(),requestHash:text('request_hash').notNull(),tokenHash:text('token_hash').notNull(),status:text('status').notNull().default('pending'),email:text('email').notNull(),firstName:text('first_name').notNull(),lastName:text('last_name').notNull(),phone:text('phone').notNull().default(''),delivery:text('delivery').notNull(),addressJson:text('address_json').notNull(),notes:text('notes').notNull().default(''),subtotalCents:integer('subtotal_cents').notNull(),shippingCents:integer('shipping_cents'),discountCents:integer('discount_cents').notNull().default(0),coupon:text('coupon'),paymentMethod:text('payment_method'),paymentNote:text('payment_note'),version:integer('version').notNull().default(1),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()
},t=>[index('idx_orders_status_created').on(t.status,t.createdAt),index('idx_orders_email').on(t.email)]);
export const orderItems=sqliteTable('order_items',{
 id:text('id').primaryKey(),orderId:text('order_id').notNull().references(()=>orders.id),productId:text('product_id').notNull().references(()=>products.id),sku:text('sku').notNull(),name:text('name').notNull(),quantity:integer('quantity').notNull(),unitCents:integer('unit_cents').notNull()
},t=>[index('idx_order_items_order').on(t.orderId)]);
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull(),updatedAt:integer('updated_at').notNull(),version:integer('version').notNull().default(1)});
export const staff=sqliteTable('staff',{email:text('email').primaryKey(),userId:text('user_id').unique(),name:text('name').notNull().default(''),role:text('role').notNull(),active:integer('active').notNull().default(1),createdAt:integer('created_at').notNull()});
export const media=sqliteTable('media',{id:text('id').primaryKey(),key:text('key').notNull().unique(),contentType:text('content_type').notNull(),size:integer('size').notNull(),name:text('name').notNull(),createdBy:text('created_by').notNull(),createdAt:integer('created_at').notNull()});
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),resource:text('resource').notNull(),detail:text('detail').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_audit_created').on(t.createdAt)]);
export const imports=sqliteTable('imports',{id:text('id').primaryKey(),source:text('source').notNull(),count:integer('count').notNull(),createdBy:text('created_by').notNull(),createdAt:integer('created_at').notNull()});
export const coupons=sqliteTable('coupons',{code:text('code').primaryKey(),percent:integer('percent').notNull(),active:integer('active').notNull().default(1),expiresAt:integer('expires_at'),version:integer('version').notNull().default(1)});
export const rateLimits=sqliteTable('rate_limits',{key:text('key').primaryKey(),hits:integer('hits').notNull(),expiresAt:integer('expires_at').notNull()});
