import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.0";
import { DEFAULTS } from "./defaults.mjs";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db = createClient(SUPABASE_URL, SERVICE_KEY, { auth: { persistSession: false, autoRefreshToken: false } });
const owners = new Set((Deno.env.get("ADMIN_EMAILS") || "gonzitassi@gmail.com").split(",").map(x => x.trim().toLowerCase()).filter(Boolean));
const roles = ["admin", "catalog", "orders"];
const statuses = ["pending", "confirmed", "awaiting_payment", "paid", "fulfilled", "cancelled"];
const origins = new Set(["https://gonzitassi.github.io", "http://127.0.0.1:4190", "http://localhost:4190"]);
const json = (data: unknown, status = 200, origin = "") => new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", ...(origin ? { "access-control-allow-origin": origin, "access-control-allow-methods": "GET,POST,PUT,OPTIONS", "access-control-allow-headers": "authorization, apikey, content-type, idempotency-key, x-file-name, x-esquiu-admin", "access-control-max-age": "86400", vary: "Origin" } : {}) } });
class HttpError extends Error { constructor(readonly status: number, message: string) { super(message); } }
const fail = (status: number, message: string): never => { throw new HttpError(status, message); };
const now = () => Date.now();
const id = () => crypto.randomUUID();
const hash = async (value: string) => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)))).map(x => x.toString(16).padStart(2, "0")).join("");
function text(value: unknown, label: string, max = 200, required = true) { if (typeof value !== "string" || value.length > max || (required && !value.trim())) fail(400, `Revisá ${label}.`); return (value as string).trim(); }
function cents(value: unknown, label = "el precio") { if (!Number.isSafeInteger(value) || (value as number) < 0 || (value as number) > 1_000_000_000_000) fail(400, `Revisá ${label}.`); return value as number; }
function email(value: unknown) { const out = text(value, "el email", 254).toLowerCase(); if (!/^[^\s@<>"']+@[^\s@<>"']+\.[^\s@<>"']+$/.test(out)) fail(400, "Email inválido."); return out; }
async function data<T>(query: PromiseLike<{ data: T | null; error: { message: string } | null }>): Promise<T> { const r = await query; if (r.error) throw Error(r.error.message); return r.data as T; }
async function body(req: Request, max = 1_000_000) { const raw = await req.arrayBuffer(); if (raw.byteLength > max) fail(413, "Los datos son demasiado grandes."); try { const value = JSON.parse(new TextDecoder().decode(raw)); if (!value || Array.isArray(value) || typeof value !== "object") throw Error(); return value as Record<string, any>; } catch { fail(400, "Datos inválidos."); } }
function publicProduct(p: any) { return { id: p.id, sku: p.sku, name: p.name, brand: p.brand, description: p.description, category: p.category, price: p.price_cents / 100, image: p.image || "assets/product-placeholder.svg", imageAlt: p.name, offer: !!p.offer, stock: null, stockMode: "untracked", availability: "confirm", maxQuantity: 99 }; }
function publicOrder(o: any) { return { id: o.id, code: o.code, status: o.status, delivery: o.delivery, subtotalCents: o.subtotal_cents, shippingCents: o.shipping_cents, discountCents: o.discount_cents, totalCents: o.shipping_cents === null ? null : o.subtotal_cents + o.shipping_cents - o.discount_cents, createdAt: o.created_at }; }
function imageValue(value: unknown) { if (value === null || value === "") return null; const v = text(value, "la imagen", 1000); const local = new Set(["assets/banner-esquiu.png", "assets/herramientas.png", "assets/automotor.png"]); if (!v.startsWith(`${SUPABASE_URL}/storage/v1/object/public/esquiu-images/`) && !local.has(v)) fail(400, "Subí la imagen desde el panel."); return v; }
function productInput(p: any) { const sku = text(p.sku, "el código", 80), name = text(p.name, "el nombre", 240), category = text(p.category || "", "el rubro", 80, false); if (category && !DEFAULTS.categories.some((c: any) => c.slug === category)) fail(400, "Rubro inválido."); const price_cents = cents(p.priceCents); if (price_cents < 1) fail(400, "El precio debe ser mayor que cero."); if (p.published && !category) fail(400, "Elegí un rubro antes de publicar."); return { sku, name, brand: text(p.brand || "", "la marca", 100, false), description: text(p.description || "", "la descripción", 4000, false), category, price_cents, image: imageValue(p.image), published: !!p.published, active: p.active !== false, offer: !!p.offer }; }
async function actor(req: Request, permission?: string) { const token = req.headers.get("authorization")?.replace(/^Bearer\s+/i, ""); if (!token) fail(401, "Iniciá sesión para acceder al panel."); const { data: auth, error } = await db.auth.getUser(token); if (error || !auth.user?.email) fail(401, "La sesión venció. Iniciá sesión nuevamente."); const user = auth.user, userEmail = user.email.toLowerCase(); let role = "";
  if (owners.has(userEmail)) role = "owner";
  else { let staff = await data<any>(db.from("staff").select("*").eq("email", userEmail).eq("active", true).maybeSingle()); if (!staff) fail(403, "Tu usuario no tiene acceso al panel."); if (staff.user_id && staff.user_id !== user.id) fail(403, "Ese email ya está vinculado a otra cuenta."); if (!staff.user_id) await data(db.from("staff").update({ user_id: user.id }).eq("email", userEmail).is("user_id", null)); staff = await data<any>(db.from("staff").select("*").eq("email", userEmail).maybeSingle()); if (staff.user_id !== user.id) fail(403, "No se pudo verificar tu usuario."); role = staff.role; }
  if (permission && !["owner", "admin", permission].includes(role)) fail(403, "Tu permiso no permite esta acción."); return { id: user.id, email: userEmail, role };
}
async function audit(user: any, action: string, resource: string, detail: Record<string, unknown> = {}) { await data(db.from("audit").insert({ actor: user.email, action, resource, detail, created_at: now() })); }
async function config() { const rows = await data<any[]>(db.from("settings").select("key,value,version")); const out: any = structuredClone(DEFAULTS); out.versions = {}; for (const r of rows) { out[r.key] = r.value; out.versions[r.key] = r.version; } return out; }
async function saveSetting(p: any, user: any) { const key = text(p.key, "la sección", 40); let value: any;
  if (key === "business") { const b = p.value; value = { ...DEFAULTS.business, name: text(b.name, "el nombre", 100), address: text(b.address, "la dirección", 240), previousAddress: text(b.previousAddress || "", "la dirección anterior", 240, false), hours: text(b.hours, "los horarios", 500), holidayHours: text(b.holidayHours || "", "los feriados", 200, false), hardware: { ...DEFAULTS.business.hardware, phone: text(b.hardware.phone, "el teléfono", 30), displayPhone: text(b.hardware.phone, "el teléfono", 30), email: email(b.hardware.email), whatsapp: b.hardware.whatsapp ? text(b.hardware.whatsapp, "el WhatsApp", 20) : null }, automotive: { ...DEFAULTS.business.automotive, phone: text(b.automotive.phone, "el teléfono", 30), displayPhone: text(b.automotive.phone, "el teléfono", 30), email: email(b.automotive.email), whatsapp: b.automotive.whatsapp ? text(b.automotive.whatsapp, "el WhatsApp", 20) : null } }; }
  else if (key === "presentation") { value = {}; for (const slot of ["hero", "lubricentro", "empresas"]) value[slot] = imageValue(p.value[slot]); if (p.value.heroSlides !== undefined) { if (!Array.isArray(p.value.heroSlides) || p.value.heroSlides.length < 1 || p.value.heroSlides.length > 5) fail(400, "El carrusel debe tener entre 1 y 5 imágenes."); const slides = p.value.heroSlides.map(imageValue); if (slides.some((image: unknown) => !image)) fail(400, "Cada espacio del carrusel necesita una imagen."); value.heroSlides = slides; value.hero = slides[0]; } if (p.value.heroMobileSlides !== undefined) { if (!Array.isArray(p.value.heroMobileSlides) || p.value.heroMobileSlides.length !== 3) fail(400, "Subí exactamente tres espacios de banner para celular."); value.heroMobileSlides = p.value.heroMobileSlides.map(imageValue); } }
  else if (key === "categories") { if (!Array.isArray(p.value) || p.value.length !== 8) fail(400, "Deben conservarse los ocho rubros."); value = DEFAULTS.categories.map((c: any) => { const x = p.value.find((r: any) => r.slug === c.slug); if (!x) fail(400, "Falta un rubro."); return { ...c, image: x.image === c.image ? c.image : imageValue(x.image) || c.image }; }); }
  else if (key === "payment") { if (!["owner", "admin"].includes(user.role)) fail(403, "Solo administración puede cambiar los datos de pago."); value = { instructions: text(p.value.instructions || "", "las instrucciones de pago", 2000, false) }; }
  else fail(400, "Sección inválida.");
  const old = await data<any>(db.from("settings").select("version").eq("key", key).maybeSingle()); if ((old?.version || 0) !== p.version) fail(409, "Otra persona cambió esta sección. Volvé a cargarla.");
  const next = await data<any[]>(db.from("settings").upsert({ key, value, updated_at: now(), version: (old?.version || 0) + 1 }, { onConflict: "key" }).select("version")); await audit(user, "settings", key); return { saved: true, version: next[0].version };
}

async function api(req: Request, origin: string) {
  const pathname = new URL(req.url).pathname;
  const functionMarker = "/esquiu-api";
  const markerIndex = pathname.indexOf(functionMarker);
  const route = markerIndex >= 0
    ? pathname.slice(markerIndex + functionMarker.length) || "/"
    : pathname.replace(/^\/functions\/v1/, "") || "/";
  const method = req.method;
  try {
    if (route === "/api/public/site" && method === "GET") { const c = await config(); delete c.versions; delete c.payment; return json({ ...c, stockMode: "untracked", orderMode: "confirmation" }, 200, origin); }
    if (route === "/api/public/products" && method === "GET") { const rows = await data<any[]>(db.from("products").select("*").eq("published", true).eq("active", true).order("name")); return json(rows.map(publicProduct), 200, origin); }
    if (route === "/media" && method === "POST") { const user = await actor(req, "catalog"), type = req.headers.get("content-type") || "", raw = new Uint8Array(await req.arrayBuffer()); if (!new Set(["image/png", "image/jpeg", "image/webp"]).has(type)) fail(400, "Usá PNG, JPG o WebP."); if (raw.length < 12 || raw.length > 5_000_000) fail(413, "La imagen está vacía o supera los 5 MB."); const sig = Array.from(raw.slice(0, 12)); const ok = type === "image/png" ? sig.slice(0, 8).join(",") === "137,80,78,71,13,10,26,10" : type === "image/jpeg" ? sig[0] === 255 && sig[1] === 216 && sig[2] === 255 : String.fromCharCode(...sig.slice(0,4)) === "RIFF" && String.fromCharCode(...sig.slice(8,12)) === "WEBP"; if (!ok) fail(400, "El contenido no coincide con el formato de la imagen."); const mediaId = id(), key = `images/${mediaId}`, name = text(req.headers.get("x-file-name") || "imagen", "el nombre", 180); const uploaded = await db.storage.from("esquiu-images").upload(key, raw, { contentType: type, upsert: false }); if (uploaded.error) throw Error(uploaded.error.message); const url = db.storage.from("esquiu-images").getPublicUrl(key).data.publicUrl; try { await data(db.from("media").insert({ id: mediaId, key, content_type: type, size: raw.length, name, created_by: user.email, created_at: now() })); await audit(user, "upload", mediaId); } catch (e) { await db.storage.from("esquiu-images").remove([key]); throw e; } return json({ id: mediaId, url }, 201, origin); }
    if (route.startsWith("/api/orders/") && (method === "GET" || route.endsWith("/accept"))) { const parts = route.match(/^\/api\/orders\/([0-9a-f-]{36})(\/accept)?$/); if (!parts) fail(404, "Pedido no encontrado."); const token = req.headers.get("authorization")?.replace(/^Bearer\s+/i, "") || ""; if (!/^[0-9a-f]{64}$/.test(token)) fail(404, "Pedido no encontrado."); const order = await data<any>(db.from("orders").select("*").eq("id", parts[1]).eq("token_hash", await hash(token)).maybeSingle()); if (!order || now() - order.created_at > 90 * 86400000) fail(404, "Pedido no encontrado o enlace vencido."); if (method === "GET" && !parts[2]) { const items = await data<any[]>(db.from("order_items").select("sku,name,quantity,unit_cents").eq("order_id", order.id)); const c = await config(); return json({ order: publicOrder(order), items, paymentInstructions: ["awaiting_payment", "paid", "fulfilled"].includes(order.status) ? c.payment?.instructions || "Contactanos para coordinar el pago." : null }, 200, origin); } if (method === "POST" && parts[2]) { if (order.status !== "confirmed" || order.shipping_cents === null) fail(409, "El pedido todavía no está listo para confirmar."); await data(db.from("orders").update({ status: "awaiting_payment", version: order.version + 1, updated_at: now() }).eq("id", order.id).eq("status", "confirmed")); return json({ accepted: true }, 200, origin); } }
    if (route === "/api/orders" && method === "POST") { const p = await body(req, 50000); if (p.website) fail(400, "No pudimos procesar la solicitud."); const key = text(req.headers.get("idempotency-key"), "la identificación del pedido", 80); if (!/^[0-9a-f-]{36}$/.test(key)) fail(400, "Identificación de pedido inválida."); const token = text(p.receiptToken, "la identificación de seguimiento", 64); if (!/^[0-9a-f]{64}$/.test(token)) fail(400, "Seguimiento inválido."); const requestHash = await hash(JSON.stringify(p)); const existing = await data<any>(db.from("orders").select("*").eq("idempotency_key", key).maybeSingle()); if (existing) { if (existing.request_hash !== requestHash) fail(409, "El pedido cambió. Volvé a revisar el carrito."); return json({ kind: "order", order: publicOrder(existing) }, 200, origin); }
      const c = p.contact || {}, d = p.delivery || {}, buyerEmail = email(c.email), first = text(c.firstName, "el nombre", 100), last = text(c.lastName, "el apellido", 100), phone = text(c.phone || "", "el teléfono", 40, false), notes = text(p.notes || "", "las notas", 2000, false); if (!["pickup", "shipping"].includes(d.type)) fail(400, "Elegí cómo querés recibir el pedido."); const address: any = {}; if (d.type === "shipping") { address.address = text(d.address, "la dirección", 300); address.city = text(d.city, "la localidad", 100); address.postalCode = text(d.postalCode, "el código postal", 20); address.province = text(d.province || "", "la provincia", 100, false); }
      if (!Array.isArray(p.items) || !p.items.length || p.items.length > 50) fail(400, "Revisá los productos del carrito."); const seen = new Set<string>(); const items = p.items.map((r: any) => { const productId = text(r.id, "el producto", 100); if (seen.has(productId) || !Number.isInteger(r.quantity) || r.quantity < 1 || r.quantity > 99) fail(400, "Revisá las cantidades del carrito."); seen.add(productId); return { id: productId, quantity: r.quantity }; }); const products = await data<any[]>(db.from("products").select("*").in("id", items.map((x: any) => x.id)).eq("active", true).eq("published", true)); if (products.length !== items.length) fail(409, "Un producto ya no está disponible para pedir. Actualizá el carrito."); let subtotal = 0; const details = items.map((r: any) => { const product = products.find((x: any) => x.id === r.id); subtotal += product.price_cents * r.quantity; return { id: id(), order_id: "", product_id: r.id, sku: product.sku, name: product.name, quantity: r.quantity, unit_cents: product.price_cents }; }); cents(subtotal, "el total del pedido"); const coupon = p.coupon ? text(p.coupon, "el cupón", 40).toUpperCase() : null; let discount = 0; if (coupon) { const cp = await data<any>(db.from("coupons").select("*").eq("code", coupon).eq("active", true).maybeSingle()); if (!cp || (cp.expires_at && cp.expires_at < now())) fail(400, "El cupón no está disponible."); discount = Math.round(subtotal * cp.percent / 100); }
      const orderId = id(), time = now(), code = `ESQ-${orderId.slice(0,8).toUpperCase()}`; let order: any; try { order = await data<any>(db.from("orders").insert({ id: orderId, code, idempotency_key: key, request_hash: requestHash, token_hash: await hash(token), status: "pending", email: buyerEmail, first_name: first, last_name: last, phone, delivery: d.type, address_json: address, notes, subtotal_cents: subtotal, shipping_cents: null, discount_cents: discount, coupon, version: 1, created_at: time, updated_at: time }).select("*").single()); for (const row of details) row.order_id = orderId; await data(db.from("order_items").insert(details)); } catch (e) { if (order) { await db.from("order_items").delete().eq("order_id", orderId); await db.from("orders").delete().eq("id", orderId); } const concurrent = await data<any>(db.from("orders").select("*").eq("idempotency_key", key).maybeSingle()); if (concurrent?.request_hash === requestHash) return json({ kind: "order", order: publicOrder(concurrent) }, 200, origin); throw e; } return json({ kind: "order", order: publicOrder(order) }, 201, origin); }

    if (!route.startsWith("/api/admin/")) fail(404, "Recurso no encontrado."); const permission = /\/products|\/import|\/media|\/settings|\/coupons/.test(route) ? "catalog" : /\/orders|\/customers/.test(route) ? "orders" : undefined; const user = await actor(req, permission);
    if (route === "/api/admin/session" && method === "GET") return json({ user, stockMode: "untracked", orderMode: "confirmation" }, 200, origin);
    if (route === "/api/admin/initial-import" && method === "GET") return json({ source: "Sin archivo", rows: [] }, 200, origin);
    if (route === "/api/admin/dashboard" && method === "GET") { const products = await data<any[]>(db.from("products").select("published")); const orders = user.role === "catalog" ? [] : await data<any[]>(db.from("orders").select("status,code,subtotal_cents,created_at").order("created_at", { ascending: false }).limit(500)); const stats = Object.entries(orders.reduce((a: any, o: any) => (a[o.status] = (a[o.status] || 0) + 1, a), {})).map(([status, count]) => ({ status, count })); return json({ products: { total: products.length, published: products.filter(p => p.published).length }, orders: stats, recent: user.role === "catalog" ? [] : orders.slice(0,6) }, 200, origin); }
    if (route === "/api/admin/products" && method === "GET") return json(await data(db.from("products").select("*").order("updated_at", { ascending: false })), 200, origin);
    if (route === "/api/admin/products" && method === "POST") { const p = productInput(await body(req, 10000)); const row = await data<any>(db.from("products").insert({ ...p, created_at: now(), updated_at: now() }).select("id").single()); await audit(user, "create", row.id, { sku: p.sku }); return json(row, 201, origin); }
    const productMatch = route.match(/^\/api\/admin\/products\/([0-9a-f-]{36})$/); if (productMatch && method === "PUT") { const input = await body(req, 10000), p = productInput(input); const changed = await data<any[]>(db.from("products").update({ ...p, version: input.version + 1, updated_at: now() }).eq("id", productMatch[1]).eq("version", input.version).select("id,version")); if (!changed.length) fail(409, "El producto cambió. Recargá antes de guardar."); await audit(user, "update", productMatch[1], { sku: p.sku, priceCents: p.price_cents, published: p.published }); return json(changed[0], 200, origin); }
    if (route === "/api/admin/import/preview" && method === "POST") return await importRows(await body(req), user, true, origin);
    if (route === "/api/admin/import/commit" && method === "POST") return await importRows(await body(req), user, false, origin);
    if (route === "/api/admin/imports" && method === "GET") return json(await data(db.from("imports").select("*").order("created_at", { ascending: false }).limit(100)), 200, origin);
    if (route === "/api/admin/media" && method === "POST") return await upload(req, user, origin);
    if (route === "/api/admin/media" && method === "GET") return json(await data(db.from("media").select("id,name,content_type,size,created_at").order("created_at", { ascending: false }).limit(200)), 200, origin);
    if (route === "/api/admin/orders" && method === "GET") return json(await data(db.from("orders").select("id,code,status,email,first_name,last_name,subtotal_cents,shipping_cents,discount_cents,created_at").order("created_at", { ascending: false }).limit(500)), 200, origin);
    const orderMatch = route.match(/^\/api\/admin\/orders\/([0-9a-f-]{36})$/); if (orderMatch) { const o = await data<any>(db.from("orders").select("*").eq("id", orderMatch[1]).maybeSingle()); if (!o) fail(404, "Pedido no encontrado."); if (method === "GET") { const items = await data(db.from("order_items").select("*").eq("order_id", o.id)); const { token_hash, request_hash, idempotency_key, ...safe } = o; return json({ order: safe, items }, 200, origin); } if (method === "PUT") { const p = await body(req, 10000), transitions: Record<string,string[]> = { pending:["confirmed","cancelled"], confirmed:["awaiting_payment","cancelled"], awaiting_payment:["paid","cancelled"], paid:["fulfilled"], fulfilled:[], cancelled:[] }; if (!statuses.includes(p.status) || !transitions[o.status].includes(p.status)) fail(409, "Ese cambio de estado no está permitido."); let shipping = o.shipping_cents; if (p.status === "confirmed") { shipping = cents(p.shippingCents, "el costo de entrega"); if (o.delivery === "pickup" && shipping !== 0) fail(400, "El retiro debe tener costo de envío cero."); } if (p.status === "paid" && (!new Set(["cash","transfer","external"]).has(p.paymentMethod) || !text(p.paymentNote,"la referencia del pago",300))) fail(400,"Indicá cómo se recibió el pago."); const changed = await data<any[]>(db.from("orders").update({ status: p.status, shipping_cents: shipping, payment_method: p.status === "paid" ? p.paymentMethod : o.payment_method, payment_note: p.status === "paid" ? p.paymentNote : o.payment_note, version: o.version + 1, updated_at: now() }).eq("id", o.id).eq("version", p.version).select("version")); if (!changed.length) fail(409,"Otra persona cambió el pedido. Recargá antes de guardar."); await audit(user,"order-status",o.id,{from:o.status,to:p.status}); return json({ saved:true,version:changed[0].version },200,origin); } }
    if (route === "/api/admin/customers" && method === "GET") { const orders = await data<any[]>(db.from("orders").select("email,first_name,last_name,phone,created_at").order("created_at", { ascending: false }).limit(5000)); const grouped = new Map<string,any>(); for (const o of orders) { const x = grouped.get(o.email) || { email:o.email,first_name:o.first_name,last_name:o.last_name,phone:o.phone,orders:0,last_order:o.created_at }; x.orders++; grouped.set(o.email,x); } return json([...grouped.values()].slice(0,500),200,origin); }
    if (route === "/api/admin/settings" && method === "GET") return json(await config(),200,origin); if (route === "/api/admin/settings" && method === "PUT") return json(await saveSetting(await body(req,50000),user),200,origin);
    if (route === "/api/admin/users") { if (user.role !== "owner") fail(403,"Solo el propietario puede administrar usuarios."); if (method === "GET") return json({ owners: [...owners], staff: await data(db.from("staff").select("email,name,role,active,created_at").order("email")) },200,origin); if (method === "POST") { const p = await body(req,3000), memberEmail = email(p.email); if (!roles.includes(p.role)) fail(400,"Permiso inválido."); if (owners.has(memberEmail)) fail(400,"El propietario se configura fuera de la lista de empleados."); const existing = await data<any>(db.from("staff").select("email,user_id").eq("email",memberEmail).maybeSingle()); if (!existing && p.active !== false) { const invite = await db.auth.admin.inviteUserByEmail(memberEmail,{redirectTo:"https://gonzitassi.github.io/ferreesquiu/web/admin/"}); if (invite.error) throw Error(invite.error.message); } await data(db.from("staff").upsert({ email:memberEmail,name:text(p.name||"","el nombre",100,false),role:p.role,active:p.active!==false,created_at:now() },{onConflict:"email"})); await audit(user,"staff",memberEmail,{role:p.role,active:p.active!==false}); return json({saved:true},200,origin); } }
    if (route === "/api/admin/coupons" && method === "GET") return json(await data(db.from("coupons").select("*").order("code")),200,origin);
    if (route === "/api/admin/coupons" && method === "PUT") { const p=await body(req,3000),code=text(p.code,"el cupón",40).toUpperCase(); if(!/^[A-Z0-9_-]+$/.test(code)||!Number.isInteger(p.percent)||p.percent<1||p.percent>100)fail(400,"Revisá el código y el descuento (1 a 100%)."); if(p.expiresAt!==null&&!Number.isSafeInteger(p.expiresAt))fail(400,"Vencimiento inválido."); await data(db.from("coupons").upsert({code,percent:p.percent,active:!!p.active,expires_at:p.expiresAt??null,version:1},{onConflict:"code"})); await audit(user,"coupon",code); return json({saved:true},200,origin); }
    if (route === "/api/admin/audit" && method === "GET") { if (!["owner","admin"].includes(user.role)) fail(403,"No tenés acceso al historial."); return json(await data(db.from("audit").select("*").order("created_at",{ascending:false}).limit(200)),200,origin); }
    if (route === "/api/admin/backup" && method === "GET") { if (!["owner","admin"].includes(user.role)) fail(403,"No tenés permiso para exportar."); const tables=["products","orders","order_items","settings","staff","media","audit","imports","coupons"]; const result:any={format:"esquiu-backup-v1",createdAt:now(),stockMode:"untracked",tables:{}}; for(const t of tables)result.tables[t]=await data(db.from(t).select("*")); for(const o of result.tables.orders){delete o.token_hash;delete o.request_hash;delete o.idempotency_key} return new Response(JSON.stringify(result),{headers:{"content-type":"application/json","content-disposition":"attachment; filename=esquiu-backup.json","access-control-allow-origin":origin,"cache-control":"no-store"}}); }
    fail(404,"Recurso no encontrado.");
  } catch (e) { if (e instanceof HttpError) return json({error:e.message},e.status,origin); console.error("Error de API",route,e); return json({error:"No pudimos completar la operación. Tus cambios no se descartaron; volvé a intentar."},503,origin); }
}

async function importRows(p: any, user: any, preview: boolean, origin: string) { if(!Array.isArray(p.rows)||!p.rows.length||p.rows.length>1000)fail(400,"Importá entre 1 y 1000 productos por archivo."); const source=text(p.source||"Excel","el origen",150), seen=new Set<string>(); const batch=p.rows.map((r:any,i:number)=>{const sku=text(r.sku,`el código de la fila ${i+1}`,80);if(seen.has(sku))fail(400,`Código repetido: ${sku}`);seen.add(sku);const price_cents=cents(r.priceCents);if(price_cents<1)fail(400,"Hay precios vacíos o iguales a cero.");return {sku,name:text(r.name,`el nombre de ${sku}`,240),brand:text(r.brand||"","la marca",100,false),price_cents};}); const old=await data<any[]>(db.from("products").select("sku,price_cents,version").order("sku")); const revision=await hash(JSON.stringify(old)),created=batch.filter((r:any)=>!old.some(x=>x.sku===r.sku)).length,priceChanges=batch.filter((r:any)=>old.some(x=>x.sku===r.sku&&x.price_cents!==r.price_cents)).map((r:any)=>({sku:r.sku,oldPriceCents:old.find(x=>x.sku===r.sku).price_cents,newPriceCents:r.price_cents})); if(preview)return json({total:batch.length,created,updated:batch.length-created,priceChanges,revision,source},200,origin); if(p.revision!==revision)fail(409,"El catálogo cambió después de la vista previa. Revisá nuevamente la importación."); for(const row of batch){const prior=old.find(x=>x.sku===row.sku);const values:any={...row,source,updated_at:now()};if(prior)values.version=prior.version+1;else Object.assign(values,{id:id(),published:false,active:true,offer:false,category:"",created_at:now()});await data(db.from("products").upsert(values,{onConflict:"sku"}));} await data(db.from("imports").insert({source,count:batch.length,created_by:user.email,created_at:now()})); await audit(user,"import","products",{source,count:batch.length,created,updated:batch.length-created}); return json({created,updated:batch.length-created,total:batch.length},200,origin); }
async function upload(req: Request, user: any, origin: string) { const type=req.headers.get("content-type")||"", raw=new Uint8Array(await req.arrayBuffer()); if(!new Set(["image/png","image/jpeg","image/webp"]).has(type))fail(400,"Usá PNG, JPG o WebP."); if(raw.length<12||raw.length>5_000_000)fail(413,"La imagen está vacía o supera los 5 MB."); const sig=Array.from(raw.slice(0,12));const ok=type==="image/png"?sig.slice(0,8).join(",")==="137,80,78,71,13,10,26,10":type==="image/jpeg"?sig[0]===255&&sig[1]===216&&sig[2]===255:String.fromCharCode(...sig.slice(0,4))==="RIFF"&&String.fromCharCode(...sig.slice(8,12))==="WEBP";if(!ok)fail(400,"El contenido no coincide con el formato de la imagen.");const mediaId=id(),key=`images/${mediaId}`,name=text(req.headers.get("x-file-name")||"imagen","el nombre",180);const uploaded=await db.storage.from("esquiu-images").upload(key,raw,{contentType:type,upsert:false});if(uploaded.error)throw Error(uploaded.error.message);const url=db.storage.from("esquiu-images").getPublicUrl(key).data.publicUrl;try{await data(db.from("media").insert({id:mediaId,key,content_type:type,size:raw.length,name,created_by:user.email,created_at:now()}));await audit(user,"upload",mediaId);}catch(e){await db.storage.from("esquiu-images").remove([key]);throw e;}return json({id:mediaId,url},201,origin); }

Deno.serve(async req => { const origin=req.headers.get("origin")||""; if(origin&&!origins.has(origin))return json({error:"Origen no permitido."},403); if(req.method==="OPTIONS")return new Response(null,{status:204,headers:{"access-control-allow-origin":origin,"access-control-allow-methods":"GET,POST,PUT,OPTIONS","access-control-allow-headers":"authorization, apikey, content-type, idempotency-key, x-file-name, x-esquiu-admin","access-control-max-age":"86400","vary":"Origin"}}); return await api(req,origin||"https://gonzitassi.github.io"); });
